name: Build library and test app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper/dists
            ~/.gradle/caches
          key: gradle-cache
      - name: Run tests
        run: ./gradlew test
      - name: Assemble library
        run: ./gradlew assembleRelease
      - name: Upload compiled AAR
        uses: actions/upload-artifact@v1
        with:
          name: ModernAndroidPreferences-release.aar
          path: library/build/outputs/aar/library-release.aar