name: Build library and test app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: "Run Gradle"
        uses: msfjarvis/setup-android@1.0
        with:
          entrypoint: ./gradlew
          args: assembleRelease
      - uses: actions/upload-artifact@v1
        with:
          name: ModernAndroidPreferences-release.aar
          path: library/build/outputs/aar/library-release.aar